package nl.paardenvriendjes.enumerations;

public enum SportType {

	BUITENRITTEN, DRAFTSPORT, DRESSUUR, ENDURANCE, FOKKEN, MENNEN, NATURALHORSEMANSHIP, POLO, RENSPORT, RINGSTEKEN, RODEO, SHOWRIJDEN, SPRINGEN, VOLTIGE, VOSSENJACHT, WESTERN
	
}
